name: gzip
description: A lightweight package for gzip compression.
version: 0.1.0
repository: https://github.com/mosuem/gzip

environment:
  sdk: ^3.2.0

dependencies:
  web: ^0.5.1

dev_dependencies:
  dart_flutter_team_lints: ^2.1.1
  test: ^1.24.0
